universal and 64-bit tentative (UNCLEAN, BAD, REFERENCE ONLY)

diff --git a/clisp/PKGBUILD b/clisp/PKGBUILD
--- a/clisp/PKGBUILD
+++ b/clisp/PKGBUILD
@@ -3,28 +3,56 @@
 # ArchLinux Maintainer: Juergen Hoetzel <juergen@archlinux.org>
 pkgname=clisp
 pkgver=2.47
-pkgrel=1
+pkgrel=2
 pkgdesc="ANSI Common Lisp interpreter, compiler and debugger"
 arch=('macx86')
 license=('GPL')
 url="http://clisp.cons.org/"
 depends=('readline' 'libsigsegv')
-makedepends=('ffcall')
+#makedepends=('ffcall')
 options=('!makeflags')
 source=(http://downloads.sourceforge.net/sourceforge/clisp/clisp-${pkgver}.tar.bz2)
 md5sums=('8fa89bb13e865fc7c7150b82682f35af')
 
 build() {
   cd ${startdir}/src/${pkgname}-${pkgver}
+
+  # straight universal fails, as there are some dependencies on type sizes
+
+  noarch_cflags="$(echo $CFLAGS | sed -e 's^-arch [a-z0-9_][a-z0-9_]*^^g')"
+  noarch_ldflags="$(echo $LDFLAGS | sed -e 's^-arch [a-z0-9_][a-z0-9_]*^^g')"
   unset CFLAGS CXXFLAGS CPPFLAGS
-  ./configure --prefix=/opt/arch --with-readline --with-ffcall src
-  cd src
-  ./makemake --prefix=/opt/arch --with-readline --with-ffcall --with-dynamic-ffi > Makefile
-  make || return 1
-  sed -i 's,http://www.lisp.org/HyperSpec/,http://www.lispworks.com/reference/HyperSpec/,g' config.lisp
-  make || return 1
-  make DESTDIR=${startdir}/pkg install || return 1
+
+  #no ffcall on x86_64 yet
+  arches="i386 x86_64"
+  binaries=""
+
+  for arch in $arches; do
+    echo "building $arch"
+    make clean
+    case "$arch" in
+        *)
+            ./configure --prefix=/opt/arch --with-readline --without-ffcall src CC="gcc -arch $arch $noarch_cflags" || return 1
+            ;;
+    esac
+
+    cd src
+    ./makemake --prefix=/opt/arch --with-readline > Makefile #--with-ffcall --with-dynamic-ffi > Makefile
+    make || return 1
+    sed -i~ -e 's,http://www.lisp.org/HyperSpec/,http://www.lispworks.com/reference/HyperSpec/,g' config.lisp
+    make || return 1
+    make DESTDIR=${startdir}/src/build/$arch install || return 1
+  done
+
+  make DESTDIR=${startdir}/pkg/ install || return 1
 
   # Remove debugging symbols
   rm -rf ${pkgdir}/opt/arch/bin/clisp.dSYM
+
+  echo "making universal binaries"
+  for binary in $binaries; do
+      rm $startdir/pkg/opt/arch/$binary
+      lipo -create $startdir/src/build/*/opt/arch/$binary -output $startdir/pkg/opt/arch/$binary
+  done
+
 }
diff --git a/ffcall/PKGBUILD b/ffcall/PKGBUILD
--- a/ffcall/PKGBUILD
+++ b/ffcall/PKGBUILD
@@ -5,7 +5,7 @@
 
 pkgname=ffcall
 pkgver=1.10
-pkgrel=3
+pkgrel=4
 pkgdesc="C library for implementing foreign function calls in embedded interpreters"
 arch=('macx86')
 url="http://www.haible.de/bruno/packages-ffcall.html"
@@ -16,12 +16,39 @@ md5sums=('2db95007e901f3bc2ae7e5a9fe9ebea4')
 
 build() {
   cd ${startdir}/src/${pkgname}-${pkgver}
-  if [ "$CARCH" = "x86_64" ]; then
-    ./configure --prefix=/opt/arch --mandir=/opt/arch/share/man --with-pic || return 1
-  else
-    ./configure --prefix=/opt/arch --mandir=/opt/arch/share/man || return 1
-  fi
-  make || return 1
+  export CFLAGS="$(echo $CFLAGS | sed -e 's^-arch [a-z0-9_][a-z0-9_]*^^g')"
+  export LDFLAGS="$(echo $LDFLAGS | sed -e 's^-arch [a-z0-9_][a-z0-9_]*^^g')"
+
+  #x86_64 fails for now
+  #apparently because OS X binary format/assembler does not support some x86_64 asm pseudo ops
+  arches="i386"
+  binaries="lib/libavcall.a lib/libcallback.a lib/libtrampoline.a lib/libvacall.a"
+
+  for arch in $arches; do
+    echo "building $arch"
+    make clean
+    case "$arch" in
+        "i386")
+            ./configure --prefix=/opt/arch --mandir=/opt/arch/share/man --with-pic CC="gcc -arch i386" CPP="gcc -E" || return 1
+            ;;
+        "x86_64")
+            ./configure --prefix=/opt/arch --mandir=/opt/arch/share/man --with-pic --build=x86_64-apple-darwin9.4.0 || return 1
+            ;;
+    esac
+
+    make || return 1
+    mkdir -p $startdir/src/build/$arch/opt/arch
+    install -d ${startdir}/src/build/$arch/opt/arch/share/man || return 1
+    make DESTDIR=${startdir}/src/build/$arch install || return 1
+  done
+
   install -d ${startdir}/pkg/opt/arch/share/man || return 1
   make DESTDIR=${startdir}/pkg/ install || return 1
+
+  echo "making universal binaries"
+  for binary in $binaries; do
+      rm $startdir/pkg/opt/arch/$binary
+      lipo -create $startdir/src/build/*/opt/arch/$binary -output $startdir/pkg/opt/arch/$binary
+  done
+
 }
